global:
  dist-dirs: &distDirs dist
  tsconfig: tsconfig.json

clean-pkg-json:
  sort-scripts: true

copy-files:
  from:
    - package.json
    - LICENSE
    - CHANGELOG.md
    - README.md
  to: *distDirs

build:
  entry: src/index.ts
  license-banner: true
  out: *distDirs
  umd-name: @aloreljs/rxutils
  skip-package-fields: true
  targets:
    - esm5
    - fesm5
    - fesm2015
    - esm2015
    - umd
  externals:
    - tslib
    - rxjs
    - rxjs/operators
    - lodash
    - lodash/isEqual
    - lodash-es
