name: Core
on:
  - push

jobs:
  lint:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        node:
          - 14.x
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v1
        name: Set up node
        with:
          node-version: ${{ matrix.node }}
          registry-url: https://npm.pkg.github.com/alorel
      - name: Set up yarn
        run: npm install -g yarn@^1.22.0
      - name: Install deps
        run: yarn install
        env:
          YARN_NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Lint
        run: yarn run tslint
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        node:
          - 14.x
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v1
        name: Set up node
        with:
          node-version: ${{ matrix.node }}
          registry-url: https://npm.pkg.github.com/alorel
      - name: Set up yarn
        run: npm install -g yarn@^1.22
      - name: Install deps
        run: yarn install
        env:
          YARN_NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        run: yarn run build
      - name: Test
        run: yarn test --forbid-only --forbid-pending
      - name: Upload coverage
        if: ${{ matrix.os != 'windows-latest' }}
        continue-on-error: true
        uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          flag-name: node-${{ matrix.node }}-on-${{ matrix.os }}
          parallel: true
  posttest:
    runs-on: ubuntu-latest
    needs: test
    continue-on-error: true
    steps:
      - name: Finalise coverage report
        uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true
  release:
    runs-on: ${{ matrix.os }}
    if: ${{ github.ref == 'refs/heads/master' }}
    needs:
      - lint
      - test
    strategy:
      matrix:
        os:
          - ubuntu-latest
        node:
          - 14.x
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 100
      - uses: actions/setup-node@v1
        name: Set up node
        with:
          node-version: ${{ matrix.node }}
          registry-url: https://npm.pkg.github.com/alorel
      - name: Set up yarn
        run: npm install -g yarn@^1.22
      - name: Install deps
        run: yarn install
        env:
          YARN_NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        run: yarn run build
      - name: Copy files
        run: node_modules/.bin/alo copy-files
      - name: Typedoc
        run: yarn run typedoc:md
      - name: Release
        run: node_modules/.bin/semantic-release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
